version: '3.8'

networks:
    default:
        name: project-network

services:

        data_sfera:
            build:
                context: ./php-fpm
                args:
                    - timezone=${TZ}
            volumes:
                - ./../data_sfera:/data_sfera:rw,cached
                - data_sfera_log:/data_sfera/var/log
            env_file:
                - .env
            depends_on:
                - mysql

        nginx:
            container_name: nginx
            build:
                context: ./nginx
                args:
                    - timezone=${TZ}
            ports:
                - "8080:80"
                - "443:443"
            depends_on:
                - data_sfera
            volumes:
                - ./../data_sfera/public:/data_sfera/public
                - ./nginx/ssl:/etc/nginx/ssl
                - ./nginx/conf.d:/etc/nginx/conf.d
                - ./nginx/nginx_log:/var/log/nginx
                - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            env_file:
                - .env
            command: /bin/bash -c "exec nginx -g 'daemon off;'"

        mysql:
            container_name: mysql
            image: mysql:latest
            env_file:
                - db/master/.env.master
            ports:
                - "3307:3306"
            volumes:
                - ./db/master/.data/mysql:/var/lib/mysql:rw

volumes:
    nginx_log:
    data_sfera_log:
    db:
        driver: local
